# Targets:
#
# clean
# stm32h743_sbx (sandbox)
# stm32f051_sbx (sandbox)
# host_tests
# host_tests_run

# ==============================================================================
#
# DIRECTORIES
#

objects_dir := ./obj
binaries_dir := ./bin
# Temporary directory for files generated by CMake:
temp_dir := ./tmp

# ==============================================================================
#
# COMMON
#

common_cxxflags := -std=c++20 -g -Wall -Wextra -MD
common_cflags := -std=c2x -Wall -Wextra -MD

# todo: -fvisibility=hidden for ARM.

# All warnings being treated as errors:
common_cflags += -Werror
common_cxxflags += -Werror

# Typical for embedded:
common_cflags += -fshort-enums
common_cxxflags += -fshort-enums
# whereas -fno-short-enums is typical for hosted.



common_ldflags :=
common_ldflags += --gc-sections
common_ldflags += --fatal-warnings
# common_ldflags += --verbose


# ==============================================================================
#
# SOCs, MCUs
#

-include arch/arm/armv6_m/stm32f0/stm32f051/stm32f051.mk
-include arch/arm/armv7e_m/stm32h7/stm32h743/stm32h743.mk

# ==============================================================================
#
# APPLICATIONS
#

-include app/stm32h743_sbx/stm32h743-sbx.mk
-include app/stm32f051_sbx/stm32f051-sbx.mk

stm32-all: stm32h743-sbx stm32f051-sbx Makefile

-include host-tests/host-tests.mk

world: stm32-all host-tests host-tests-run Makefile

# ==============================================================================
#
# CLEAN
#

.PHONY: clean
clean:
	$(info INFO: CLEANING)
	@rm -rf $(objects_dir)
	@rm -rf $(binaries_dir)
	@rm -rf $(temp_dir)

# ==============================================================================
