#include "../../if/mcu/nvic.h"
#include "arch/arm/armv7e_m/stm32h7/stm32h743/nvic.h"
#include "if/mcu/chrono.h"

extern "C" void resetHandler();

using stm32h743::nvic::reservedHandler;

namespace nvic {
namespace {
__attribute__((section(".exception_vectors"), used)) /* 'used' attribute is similar to KEEP() */
constexpr stm32h743::nvic::ExceptionVectors exceptionVectors = {
	resetHandler, // Exception number = 1
	nvic::nmiHandler, // IRQ number = -14
	nvic::hardFaultHandler,
	nvic::memManageHandler,
	nvic::busFaultHandler,
	nvic::usageFaultHandler,
	reservedHandler,
	reservedHandler,
	reservedHandler,
	reservedHandler,
	nvic::svcISR,
	nvic::debugMonHandler,
	reservedHandler,
	nvic::pendsvISR,
	nvic::sysTickISR, // SysTick_Handler,  // IRQ number = -1
};

// TODO: constexpr array maker
__attribute__((section(".interrupt_vectors"), used)) /* 'used' attribute is similar to KEEP() */
constexpr stm32h743::nvic::InterruptVectors interrupsVectors = {
	nvic::defaultHandler, // WWDG_IRQHandler, // IRQ0
	nvic::defaultHandler, // PVD_AVD_IRQHandler,
	nvic::defaultHandler, // TAMP_STAMP_IRQHandler,
	nvic::defaultHandler, // RTC_WKUP_IRQHandler,
	nvic::defaultHandler, // FLASH_IRQHandler,
	nvic::defaultHandler, // RCC_IRQHandler,
	nvic::defaultHandler, // EXTI0_IRQHandler,
	nvic::defaultHandler, // EXTI1_IRQHandler,
	nvic::defaultHandler, // EXTI2_IRQHandler,
	nvic::defaultHandler, // EXTI3_IRQHandler,
	nvic::defaultHandler, // EXTI4_IRQHandler,
	nvic::defaultHandler, // DMA1_Stream0_IRQHandler,
	nvic::defaultHandler, // DMA1_Stream1_IRQHandler,
	nvic::defaultHandler, // DMA1_Stream2_IRQHandler,
	nvic::defaultHandler, // DMA1_Stream3_IRQHandler,
	nvic::defaultHandler, // DMA1_Stream4_IRQHandler,
	nvic::defaultHandler, // DMA1_Stream5_IRQHandler,
	nvic::defaultHandler, // DMA1_Stream6_IRQHandler,
	nvic::defaultHandler, // ADC_IRQHandler,
	nvic::defaultHandler, // FDCAN1_IT0_IRQHandler,
	nvic::defaultHandler, // FDCAN2_IT0_IRQHandler,
	nvic::defaultHandler, // FDCAN1_IT1_IRQHandler,
	nvic::defaultHandler, // FDCAN2_IT1_IRQHandler,
	nvic::defaultHandler, // EXTI9_5_IRQHandler,
	nvic::defaultHandler, // TIM1_BRK_IRQHandler,
	nvic::defaultHandler, // TIM1_UP_IRQHandler,
	nvic::defaultHandler, // TIM1_TRG_COM_IRQHandler,
	nvic::defaultHandler, // TIM1_CC_IRQHandler,
	chrono::steady_clock::overflow, /*TIM2_IRQHandler*/ // IRQ28
	chrono::high_resolution_clock::overflow, /*TIM3_IRQHandler*/ // IRQ29
	nvic::defaultHandler, // TIM4_IRQHandler,
	nvic::defaultHandler, // I2C1_EV_IRQHandler,
	nvic::defaultHandler, // I2C1_ER_IRQHandler,
	nvic::defaultHandler, // I2C2_EV_IRQHandler,
	nvic::defaultHandler, // I2C2_ER_IRQHandler,
	nvic::defaultHandler, // SPI1_IRQHandler,
	nvic::defaultHandler, // SPI2_IRQHandler,
	nvic::defaultHandler, // USART1_IRQHandler,
	nvic::defaultHandler, // USART2_IRQHandler,
	nvic::defaultHandler, // USART3_IRQHandler,
	nvic::defaultHandler, // EXTI15_10_IRQHandler,
	nvic::defaultHandler, // RTC_Alarm_IRQHandler,
	reservedHandler,
	nvic::defaultHandler, // TIM8_BRK_TIM12_IRQHandler,
	nvic::defaultHandler, // TIM8_UP_TIM13_IRQHandler,
	nvic::defaultHandler, // TIM8_TRG_COM_TIM14_IRQHandler,
	nvic::defaultHandler, // TIM8_CC_IRQHandler,
	nvic::defaultHandler, // DMA1_Stream7_IRQHandler,
	nvic::defaultHandler, // FMC_IRQHandler,
	nvic::defaultHandler, // SDMMC1_IRQHandler,
	nvic::defaultHandler, // TIM5_IRQHandler,
	nvic::defaultHandler, // SPI3_IRQHandler,
	nvic::defaultHandler, // UART4_IRQHandler,
	nvic::defaultHandler, // UART5_IRQHandler,
	nvic::defaultHandler, // TIM6_DAC_IRQHandler,
	nvic::defaultHandler, // TIM7_IRQHandler,
	nvic::defaultHandler, // DMA2_Stream0_IRQHandler,
	nvic::defaultHandler, // DMA2_Stream1_IRQHandler,
	nvic::defaultHandler, // DMA2_Stream2_IRQHandler,
	nvic::defaultHandler, // DMA2_Stream3_IRQHandler,
	nvic::defaultHandler, // DMA2_Stream4_IRQHandler,
	nvic::defaultHandler, // ETH_IRQHandler,
	nvic::defaultHandler, // ETH_WKUP_IRQHandler,
	nvic::defaultHandler, // FDCAN_CAL_IRQHandler,
	reservedHandler,
	reservedHandler,
	reservedHandler,
	reservedHandler,
	nvic::defaultHandler, // DMA2_Stream5_IRQHandler,
	nvic::defaultHandler, // DMA2_Stream6_IRQHandler,
	nvic::defaultHandler, // DMA2_Stream7_IRQHandler,
	nvic::defaultHandler, // USART6_IRQHandler,
	nvic::defaultHandler, // I2C3_EV_IRQHandler,
	nvic::defaultHandler, // I2C3_ER_IRQHandler,
	nvic::defaultHandler, // OTG_HS_EP1_OUT_IRQHandler,
	nvic::defaultHandler, // OTG_HS_EP1_IN_IRQHandler,
	nvic::defaultHandler, // OTG_HS_WKUP_IRQHandler,
	nvic::defaultHandler, // OTG_HS_IRQHandler,
	nvic::defaultHandler, // DCMI_IRQHandler,
	reservedHandler,
	nvic::defaultHandler, // RNG_IRQHandler,
	nvic::defaultHandler, // FPU_IRQHandler,
	nvic::defaultHandler, // UART7_IRQHandler,
	nvic::defaultHandler, // UART8_IRQHandler,
	nvic::defaultHandler, // SPI4_IRQHandler,
	nvic::defaultHandler, // SPI5_IRQHandler,
	nvic::defaultHandler, // SPI6_IRQHandler,
	nvic::defaultHandler, // SAI1_IRQHandler,
	nvic::defaultHandler, // LTDC_IRQHandler,
	nvic::defaultHandler, // LTDC_ER_IRQHandler,
	nvic::defaultHandler, // DMA2D_IRQHandler,
	nvic::defaultHandler, // SAI2_IRQHandler,
	nvic::defaultHandler, // QUADSPI_IRQHandler,
	nvic::defaultHandler, // LPTIM1_IRQHandler,
	nvic::defaultHandler, // CEC_IRQHandler,
	nvic::defaultHandler, // I2C4_EV_IRQHandler,
	nvic::defaultHandler, // I2C4_ER_IRQHandler,
	nvic::defaultHandler, // SPDIF_RX_IRQHandler,
	nvic::defaultHandler, // OTG_FS_EP1_OUT_IRQHandler,
	nvic::defaultHandler, // OTG_FS_EP1_IN_IRQHandler,
	nvic::defaultHandler, // OTG_FS_WKUP_IRQHandler,
	nvic::defaultHandler, // OTG_FS_IRQHandler,
	nvic::defaultHandler, // DMAMUX1_OVR_IRQHandler,
	nvic::defaultHandler, // HRTIM1_Master_IRQHandler,
	nvic::defaultHandler, // HRTIM1_TIMA_IRQHandler,
	nvic::defaultHandler, // HRTIM1_TIMB_IRQHandler,
	nvic::defaultHandler, // HRTIM1_TIMC_IRQHandler,
	nvic::defaultHandler, // HRTIM1_TIMD_IRQHandler,
	nvic::defaultHandler, // HRTIM1_TIME_IRQHandler,
	nvic::defaultHandler, // HRTIM1_FLT_IRQHandler,
	nvic::defaultHandler, // DFSDM1_FLT0_IRQHandler,
	nvic::defaultHandler, // DFSDM1_FLT1_IRQHandler,
	nvic::defaultHandler, // DFSDM1_FLT2_IRQHandler,
	nvic::defaultHandler, // DFSDM1_FLT3_IRQHandler,
	nvic::defaultHandler, // SAI3_IRQHandler,
	nvic::defaultHandler, // SWPMI1_IRQHandler,
	nvic::defaultHandler, // TIM15_IRQHandler,
	nvic::defaultHandler, // TIM16_IRQHandler,
	nvic::defaultHandler, // TIM17_IRQHandler,
	nvic::defaultHandler, // MDIOS_WKUP_IRQHandler,
	nvic::defaultHandler, // MDIOS_IRQHandler,
	nvic::defaultHandler, // JPEG_IRQHandler,
	nvic::defaultHandler, // MDMA_IRQHandler,
	reservedHandler,
	nvic::defaultHandler, // SDMMC2_IRQHandler,
	nvic::defaultHandler, // HSEM1_IRQHandler,
	reservedHandler,
	nvic::defaultHandler, // ADC3_IRQHandler,
	nvic::defaultHandler, // DMAMUX2_OVR_IRQHandler,
	nvic::defaultHandler, // BDMA_Channel0_IRQHandler,
	nvic::defaultHandler, // BDMA_Channel1_IRQHandler,
	nvic::defaultHandler, // BDMA_Channel2_IRQHandler,
	nvic::defaultHandler, // BDMA_Channel3_IRQHandler,
	nvic::defaultHandler, // BDMA_Channel4_IRQHandler,
	nvic::defaultHandler, // BDMA_Channel5_IRQHandler,
	nvic::defaultHandler, // BDMA_Channel6_IRQHandler,
	nvic::defaultHandler, // BDMA_Channel7_IRQHandler,
	nvic::defaultHandler, // COMP1_IRQHandler,
	nvic::defaultHandler, // LPTIM2_IRQHandler,
	nvic::defaultHandler, // LPTIM3_IRQHandler,
	nvic::defaultHandler, // LPTIM4_IRQHandler,
	nvic::defaultHandler, // LPTIM5_IRQHandler,
	nvic::defaultHandler, // LPUART1_IRQHandler,
	reservedHandler,
	nvic::defaultHandler, // CRS_IRQHandler,
	reservedHandler,
	nvic::defaultHandler, // SAI4_IRQHandler,
	reservedHandler,
	reservedHandler,
	nvic::defaultHandler, // WAKEUP_PIN_IRQHandler // IRQ149
};
}
}
